### PR TITLE
Set mitx nginx logging format to match our other applications

### PR DESCRIPTION
**Pull request by shaidar**
#### What are the relevant tickets?
[Issue#204](https://github.com/mitodl/salt-ops/issues/204)

#### What's this PR do?
Sets mitx nginx logging format to match the our other applications

### CODE REVIEW

**Comment by shaidar** [comment]
@blarghmatey Doesn't the edxapp role already call the nginx role and install that as part of the deployment?

**Comment by blarghmatey** [comment]
It calls the Ansible Nginx role, but not the Salt one

**Comment by blarghmatey** [comment]
Honestly, it might be more straightforward to just do a file.managed directly as part of the edx.prod state

**Comment by blarghmatey** [comment]
That looks good, but we'll still want to add the log format name to the ansible vars as well to be sure that it gets picked up.

**Comment by blarghmatey** [comment]
:+1:

**Pull request merged**
