### PR TITLE
add mailchimp settings for newsletter on home page

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

fixes https://github.com/mitodl/ocw-www/issues/52

#### What's this PR do?

Adds Mailchimp settings, which I hope will be available to the ocw-www build. 

#### How should this be manually tested?

Visit the ocwnext home page and enter your email address in the newsletter form:

image

### CODE REVIEW

**Comment by pdpinch** [comment]
@noisecapella @shaidar does this look right?

**Comment by pdpinch** [comment]
Also, should we alphabetize these settings?

**Comment by shaidar** [comment]
👍 Alphabetizing settings would sure keep things easier to read, but not necessary. Maybe next PR, I'll reorganize them

**Comment by pdpinch** [comment]
@shaidar @markbreedlove can you let me know how/if/when I can expect to see these settings on RC?

**Comment by shaidar** [comment]
@pdpinch I'm a bit unclear with u mentioning RC cause the PR is against production pillar. Are those production values or QA/RC values?

**Pull request merged**
