### PR TITLE
Added Touchstone/SAML settings for OCW Studio

### PR DESCRIPTION
**Pull request by rhysyngsun**
#### What are the relevant tickets?
Part of https://github.com/mitodl/ocw-studio/issues/62

#### What's this PR do?
Adds environment variables needed to get

#### How should this be manually tested?
Deploy to CI/RC and ensure the app still runs

### CODE REVIEW

**Comment by shaidar** [comment]
@rhysyngsun Looks good. Gonna request the certs from IS&T and once I have those in vault, will update you and we can get this merged and deployed.

**Comment by blarghmatey** [comment]
For the SAML certs we just generate them and provide the public key to them. We don't need to have them create it.

**Comment by rhysyngsun** [comment]
@shaidar I think we need to have the saml metadata API in place before we can contact IS&T, that's being added in https://github.com/mitodl/ocw-studio/pull/165

**Comment by shaidar** [comment]
Yes we do as they'll have to make a request to it before they are able to add it. Working on the certs and adding to vault

**Comment by shaidar** [comment]
👍

**Pull request merged**
