### PR TITLE
Adapt to restructured Nginx formula

### PR DESCRIPTION
**Pull request by markbreedlove**
See https://github.com/mitodl/nginx-formula/pull/2
This should only be merged after that PR is merged.

#### What are the relevant tickets?

https://github.com/mitodl/salt-ops/issues/980

#### What's this PR do?

* Change salt/top.sls to reference restructured nginx formula, which removes the `ng` state.

* Remove the `ng` property of various pillar files, which changes their indentation.

### CODE REVIEW

**Comment by blarghmatey** [comment]
This will probably also require an update to the `top.sls` file in the salt directory for the nginx states execution.

**Comment by markbreedlove** [comment]
@blarghmatey : `salt/top.sls` got those changes in this commit: https://github.com/mitodl/salt-ops/commit/57c56d877#diff-70875c5ef95237363dff632f2704dd00

**Comment by blarghmatey** [comment]
:+1: just don't merge yet.

**Comment by markbreedlove** [comment]
Per @blarghmatey in Slack, this is OK to merge now.

**Pull request merged**
