### PR TITLE
Google Drive settings for OCW Studio

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-studio/issues/443

#### What's this PR do?
Adds settings for Google Drive integration in OCW Studio

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
Made a guess on where in vault the service credentials should be stored.

### CODE REVIEW

**Comment by blarghmatey** [comment]
This will break in CI because there's no value set for that environment. Even if it's an empty string that would be fine.

**Comment by mbertrand** [comment]
Added a value for CI

**Comment by blarghmatey** [comment]
:+1:

**Comment by mbertrand** [comment]
@blarghmatey are there values for `__vault__::secret-open-courseware/ocw-studio/{{ environment }}/gdrive-service-json>data>value` yet (service account credentials JSON)? If not, I should probably hold off on merging this?

**Comment by blarghmatey** [comment]
No, I haven't even started setting up a service account for that yet. @shaidar can you work on that? @mbertrand can you detail the permissions, APIs needed, etc. for the service account? Or link to some documentation?

**Comment by mbertrand** [comment]
Needs to be a service account with "domain-wide delegation" enabled, Google Drive API enabled, and owner permissions to the specified team drive on RC, production (id's are in this PR).

**Comment by shaidar** [comment]
Service account setup. This PR can be merged now

**Pull request merged**
