### PR TITLE
Added marketing links for edX footer

### PR DESCRIPTION
**Pull request by blarghmatey**
#### What are the relevant tickets?
https://github.com/mitodl/mitxpro/issues/832

#### What's this PR do?
Adds link map for edX footer

### CODE REVIEW

**Comment by shaidar** [comment]
How does that play with [this](https://github.com/mitodl/salt-ops/blob/master/pillar/edx/ansible_vars/xpro.sls#L43-L46)?

**Comment by blarghmatey** [comment]
Apparently they are two separate things :man_shrugging:

**Comment by shaidar** [comment]
👍

**Comment by shaidar** [comment]
@blarghmatey This appear to be causing the following issue:
```
2019-08-01 14:15:08,510 ERROR 23073 [django.request] exception.py:135 - Internal Server Error: /home/
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/course.py", line 563, in course_listing
    u'optimization_enabled': optimization_enabled
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 169, in render_to_response
    return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string
    return template.render(dictionary, request)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render
    return self.mako_template.render_unicode(**context_dictionary)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
    as_unicode=True)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mako_cms/f13f950116d269293ac438cd8e2ded58/base.html.py", line 268, in render_body
    runtime._include_file(context, u'widgets/footer.html', _template_uri)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/tmp/mako_cms/f13f950116d269293ac438cd8e2ded58/mitxpro-theme/cms/templates/widgets/footer.html.py", line 51, in render_body
    __M_writer(filters.html_escape(filters.decode.utf8(marketing_link('PRIVACY'))))
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 64, in marketing_link
    return reverse(link_map[name])
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
NoReverseMatch: u'https' is not a registered namespace
```

**Comment by blarghmatey** [comment]
It seems like it doesn't support full URLs and just wants a relative route...

**Comment by shaidar** [comment]
@blarghmatey Should be revert this so that a scheduled run doesn't impact running instances?

**Pull request merged**
