### PR TITLE
Convert Vector states to use Vector's new DSL

### PR DESCRIPTION
**Pull request by markbreedlove**
This updates the existing Vector configurations to use Vector's new Vector Remap Language, which has suddenly superceded the transforms that used to be available.

### CODE REVIEW

**Comment by markbreedlove** [comment]
I'm going to have it preserve a `time` field in addition to `@timestamp` to make it easier to eventually change our index patterns and get away from the funny `@timestamp` nomenclature. Commit coming ...

**Comment by blarghmatey** [comment]
Looks good :+1:

**Comment by blarghmatey** [comment]
Looks good :+1:

**Comment by markbreedlove** [comment]
Thanks. I'm sorry, but I forget exactly what we ended up deciding. I've added a "raw_message" field to the tracking log, but did we want to do that for any other ones? We'd discussed the storage implications, and I think we didn't want to do that for everything.

**Comment by blarghmatey** [comment]
I think that for now we should skip on adding the raw message to tracking logs so as to avoid fouling any of the downstream consumer logic.

**Comment by blarghmatey** [comment]
Let's merge this as is and then circle back on raw messages as we get further along with the rest of our logging.

**Pull request merged**
