### PR TITLE
WIP: remove deprecated feature flags

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

none

#### What's this PR do?

removes some deprecated feature flags

#### How should this be manually tested?

Does an AMI build and does the app launch?

#### Any background context you want to provide?

See https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/34734726/edX+Feature+Flags
 for a list of edX feature flags

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1:

**Comment by shaidar** [comment]
@pdpinch Can this be merged or is it still a WIP?

**Comment by pdpinch** [comment]
Still WIP. We should at least wait to see the outcome of the next edX hackathon, where there's a project to clean up some of the older feature flags.

**Comment by shaidar** [comment]
@pdpinch Anything new on this?

**Comment by shaidar** [comment]
@pdpinch Should we merge this and then open a new PR (if needed) to remove any additional unnecessary flags?

**Comment by shaidar** [comment]
@blarghmatey Should we just merge this and whenever there are any other deprecated keys we can open up another PR for them?

**Comment by blarghmatey** [comment]
Yes, might as well

On Jun 14, 2019 2:15 PM, Sar <notifications@github.com> wrote:

@blarghmatey<https://github.com/blarghmatey> Should we just merge this and whenever there are any other deprecated keys we can open up another PR for them?

-

**Pull request merged**
