### PR TITLE
s3 buckets for ocw-next search index

### PR DESCRIPTION
**Pull request by abeglova**
#### What are the relevant tickets?
https://github.com/mitodl/open-discussions/issues/3484
and
https://github.com/mitodl/open-discussions/issues/3486

#### What's this PR do?
This PR adds the required .env variables for adding ocw-next course data to search

#### How should this be manually tested?
NA

#### Where should the reviewer start?
NA

### CODE REVIEW

**Comment by blarghmatey** [comment]
:+1:

**Comment by blarghmatey** [comment]
The env settings look good but it seems that we need to add them to the config block further down in the file to make use of them.

**Comment by abeglova** [comment]
Oops fixed

**Comment by blarghmatey** [comment]
:+1:

**Pull request merged**
