### PR TITLE
New open-discussions env variables for importing MITx Online courses

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
https://github.com/mitodl/open-discussions/issues/3637
https://github.com/mitodl/open-discussions/issues/3636

#### What's this PR do?
Adds env variables required to import MITx Online courses into the open-discussions search index.

#### How should this be manually tested?
N/A

### CODE REVIEW

**Comment by shaidar** [comment]
Since this only applies to production, might be best to filter on that with something like [this](https://github.com/mitodl/salt-ops/blob/2e7ba69a0deb9be47b90c2cc72f8287d6f5e8f2d/pillar/heroku/discussions.sls#L156):
```
{% if env_data.env_name == 'production' %}
```

**Comment by mbertrand** [comment]
> Since this only applies to production, might be best to filter on that with something like this

I was thinking we'd want the env variables on RC too for testing purposes, to make sure the production mitx-online courses get imported properly.

**Comment by shaidar** [comment]
In that case, I would just add it under [this](https://github.com/mitodl/salt-ops/blob/2e7ba69a0deb9be47b90c2cc72f8287d6f5e8f2d/pillar/heroku/discussions.sls#L156) conditional

**Comment by shaidar** [comment]
👍

**Pull request merged**
