### PR TITLE
Added monit alert to notify slack when LMS page is returning a 503 error

### PR DESCRIPTION
**Pull request by shaidar**
#### What are the relevant tickets?
[Issue#511](https://github.com/mitodl/salt-ops/issues/511)

#### What's this PR do?
Monit alert to notify slack when LMS page is returning a 503 error

### CODE REVIEW

**Comment by blarghmatey** [comment]
You'll need to add this to the pillar top file for targeting. Also, is it possible to make this flag the `devopseng` user in the slack message so that we don't miss it?

**Comment by blarghmatey** [comment]
Also, this won't work if we're running it on the edX servers since we're overriding the DNS lookup with the /etc/hosts hack that we set up for xqueue submissions.

**Comment by shaidar** [comment]
I'll change it to have a static value to the LMS DNS entry then so that it runs on an instance in operations like you originally requested. 

On the matter of flagging `devopseng`, I think we need to have a conversation about alerts in general as it feels like we're heading down the dangerous path of too much noise. You had previously mentioned possibly tagging alert by level of severity which sounds like an interesting idea.

**Comment by blarghmatey** [comment]
I think that is a valuable discussion to have. Let's chat about it today after standup.

**Comment by blarghmatey** [comment]
:-1:

**Pull request merged**
