### PR TITLE
Consul caddy

### PR DESCRIPTION
**Pull request by shaidar**
#### What's this PR do?
- Added Caddy config and modified top file
- Updated consul version
- Added consul-esm and config
- Removed xPRO RDS backend from env_settings

### CODE REVIEW

**Comment by blarghmatey** [comment]
Looks good, just need to add the Consul state to the salt top file as well so that it gets included in the highstate.

**Comment by shaidar** [comment]
@blarghmatey What Consul state? I added the consul caddy to the top pillar file.

**Comment by blarghmatey** [comment]
Sorry, I meant adding the Caddy state `salt/top.sls` for the Consul servers.

**Comment by blarghmatey** [comment]
:+1:

**Pull request merged**
